<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Blockcypher API KEY
    |--------------------------------------------------------------------------
    |
    | This key is used by the Blockcypher API.
    | You can obtain an API key here: https://accounts.blockcypher.com/tokens
    |
    */

    'token' => env('BLOCKCYPHER_TOKEN'),

    /*
    |--------------------------------------------------------------------------
    | Blockcypher BACKEND WALLET
    |--------------------------------------------------------------------------
    |
    | This key is generated by using the Blockcypher Testing Network.
    | You can obtain an API key here: https://accounts.blockcypher.com/tokens
    |
    */

    'system_public_address' => env('BLOCKCYPHER_PUBLIC_ADDRESS', 'C3SPXmwuAtoE5U4j75TwxXDM4iCsMZFNmV'),
    
    'system_public_key' => env('BLOCKCYPHER_PUBLIC_KEY', '0306abe1e3b618a845c432b8b52244f6dfe5385a5fd1d20a6f0ca2a10f54a8dd43'),

    'system_private_key' => env('BLOCKCYPHER_PRIVATE_KEY', 'd103370737331e166b0531f6b9deeb06385201de12e3876f340fc7f7a85205df'),
    
];